/*
 * ultrasonic_sensor.c
 *
 *  Created on: Oct 21, 2023
 *      Author: DELL
 */

 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: source file for ultrasonic sensor driver
 *
 * Author: aya ashraf
 *
 *******************************************************************************/

#include"ultrasonic.h"
#include "icu.h"
#include  <util/delay.h>

/********************************************************************************
 * 								Private Global variables
 ********************************************************************************/

uint8 g_edgeCount = 0; /*to count the edges*/
uint16 g_timeHigh = 0; /*to get the from the first rising edge*/
uint16 g_timePeriod = 0; /*to get the from the first falling edge*/
uint16 g_timePeriodPlusHigh = 0; /*global variable to hold the value of the the period time plus high time */


/********************************************************************************
 * 								Functions definition
 ********************************************************************************/
/*
 * Description
 *Initialize the ICU driver as required.
 *Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the
GPIO driver.
 */
void Ultrasonic_init(void)
{

	/* Create configuration structure for ICU driver */
	ICU_ConfigType ICU_Configurations = {F_CPU_8,RISING};
	ICU_init(&ICU_Configurations);
	/* Set the Call back function pointer in the ICU driver */
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	/*set up the direction for trigger pin to be output*/
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,PIN_OUTPUT);


}

/*
 * Description
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	/*to generate high pulse with duration 10 us to trigger ultrasonic */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,LOGIC_HIGH);
	/*waiting for the required time to complete the pulse width which is at least 10 us*/
	_delay_us(10);
	/*send low voltage signal to the trigger pin to end the required pulse*/
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,LOGIC_LOW);
}

/*
 * Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 ultrasonic_distance=0;
	while(1)
	{
	/*Sending the trigger pulse to the trigger pin*/
	Ultrasonic_Trigger();
	if(g_edgeCount==4)
	{
		/*we have finished the measurements of this time so we
		 * need to repeat this cycle again so initialize the number
		 * of counts to zero
		 */
		g_edgeCount=0;

	ultrasonic_distance= (uint16)((float)(g_timePeriodPlusHigh - g_timePeriod) / 58.0);
	return ultrasonic_distance;
	}
	}

}

/* Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor
*/

void Ultrasonic_edgeProcessing(void)
{
	/*counts number of edges*/
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/* Clear the timer counter register to start measurements from the
		 * first detected rising edge*/
		ICU_clearTimerValue();

		/* Detect the falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time ECHO value */
		g_timeHigh = ICU_getInputCaptureValue();

		/* Detect the next rising edge to calculate the period time*/
		ICU_setEdgeDetectionType(RISING);

	}
	else if(g_edgeCount == 3)
	{
		/* Store the Period time value */
		g_timePeriod = ICU_getInputCaptureValue();

		/* Detect the falling edge to calculate
		 * the period time plus the high ECHO time */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 4)
	{
		/* Store the Period time value + High time value */
		g_timePeriodPlusHigh = ICU_getInputCaptureValue();

		/* Clear the timer counter register to start measurements again */
		ICU_clearTimerValue();

		/* Detect the rising edge */
		ICU_setEdgeDetectionType(RISING);

	}

}


